- name: Create calculator container using calc image
  hosts: client1
  become: yes
  tasks:
    - name: pull the docker image from hub 'murphy961/spe_devops'
      shell:
        docker pull rupen28/calculator-devopstools-webapp:latest
    - name: create container using pulled image
      shell:
        docker rm rupen_calc&&docker run -itd -v ${PWD}/logs:/logs --name rupen_calc rupen28/calculator-devopstools-webapp:latest